title: My Site
logo: /assets/img/logo.jpg
description: This is a site description

### Theme
# theme: jekyll-theme-cayman
remote_theme: pmarsceill/just-the-docs

### Color scheme supports "light" (default) and "dark"
color_scheme: light

#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
